services/app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  namespace :api do
    resources :lessons, only: [] do
      member do
        post :check
      end
    end
  end

  scope module: :web do
    root 'home#index'
    get 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    get '/403', to: 'errors#forbidden', as: :not_forbidden_errors
    get '/404', to: 'errors#not_found', as: :not_found_errors
    match '/500', to: 'errors#server_error', via: :all

    resources :pages, only: [:show]
    resource :session, only: %i[new create destroy]
    resource :locale, only: [] do
      member do
        get :switch
      end
    end
    resources :users, only: %i[new create]
    resource :remind_password, only: %i[new create]
    resource :password, only: %i[edit update]

    resources :languages, only: [:show] do
      scope module: :languages do
        resources :lessons, only: [:show] do
          get :next_lesson, on: :member
          get :prev_lesson, on: :member
        end
      end
    end

    namespace :admin do
      root 'home#index'

      resources :languages, only: %i[index new edit update create] do
        scope module: :languages do
          resources :versions, only: %i[index create]
        end
      end
    end

    namespace :account do
      resource :profile, only: %i[edit update destroy]
    end
  end
end

services/app/app/views/layouts/shared/_flash.html.slim
- flash.each do |name, msg|
  - let 'error' => 'danger', 'warning' => 'warning', 'info' => 'info', 'success' => 'success', 'alert' => 'warning', 'recaptcha_error' => 'danger' do |mapping|
    .alert.alert-dismissable.rounded-0.mb-0[class="alert-#{mapping[name]}"]
      button.close type='button' data-dismiss='alert' aria-hidden='true' &times;
      = msg

services/app/app/views/layouts/shared/_head.html.slim
meta charset='utf-8'
meta http-equiv='X-UA-Compatible' content='IE=Edge'
meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'
= yield :meta
title = title
= csrf_meta_tags
= csp_meta_tag
= include_gon(init: true)
= javascript_pack_tag 'application'
= stylesheet_pack_tag 'application', media: 'all'
- if Rails.env.production?
  = render 'layouts/deps/gtm_head'

services/app/app/views/layouts/shared/_language_switcher.html.slim
- # FIXME
- I18n.available_locales.without(I18n.locale).each do |locale|
  = link_to switch_locale_path(locale: locale) do
    = image_tag "flag-#{locale}.svg", width: 25, alt: "switch language to #{locale}"

services/app/app/views/layouts/shared/_nav.html.slim
nav.px-3.navbar.navbar-light.navbar-expand-md.bg-white.shadow-sm.flex-shrink-0
  a.navbar-brand(href='/')
    = image_tag 'logo.png', width: 30, alt: 'Code Basics logo'

  button.navbar-toggler(
    type='button' data-toggle='collapse'
    data-target='#navbarToggler' aria-controls='navbarToggler'
    aria-expanded='false' aria-label=t('.toggle_navigation')
  )
    span.navbar-toggler-icon
  #navbarToggler.collapse.navbar-collapse
    ul.flex-grow-1.navbar-nav
      li.nav-item.dropdown.mr-md-2
        a#dropdownMenuLink.nav-link.dropdown-toggle href='#' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'
          = t('.change_course')
        .dropdown-menu.dropdown-menu-columns.dropdown-menu-arrow aria-labelledby='dropdownMenuLink'
          = link_to language_path('php'), class: 'dropdown-item d-flex align-items-center'
            span.dropdown-item-icon.fab.fa-php.d-flex.justify-content-center.align-items-center
            span.dropdown-item-text = t('human_languages.php')
          = link_to language_path('javascript'), class: 'dropdown-item d-flex align-items-center'
            span.dropdown-item-icon.fab.fa-js-square.d-flex.justify-content-center.align-items-center
            span.dropdown-item-text = t('human_languages.javascript')
          = link_to language_path('python'), class: 'dropdown-item d-flex align-items-center'
            span.dropdown-item-icon.fab.fa-python.d-flex.justify-content-center.align-items-center
            span.dropdown-item-text = t('human_languages.python')
          = link_to language_path('java'), class: 'dropdown-item d-flex align-items-center'
            span.dropdown-item-icon.fab.fa-java.d-flex.justify-content-center.align-items-center
            span.dropdown-item-text = t('human_languages.java')
          = link_to language_path('html'), class: 'dropdown-item d-flex align-items-center'
            span.dropdown-item-icon.fab.fa-html5.d-flex.justify-content-center.align-items-center
            span.dropdown-item-text = t('human_languages.html')
          = link_to language_path('css'), class: 'dropdown-item d-flex align-items-center'
            span.dropdown-item-icon.fab.fa-css3-alt.d-flex.justify-content-center.align-items-center
            span.dropdown-item-text = t('human_languages.css')
          = link_to language_path('racket'), class: 'dropdown-item d-flex align-items-center'
            span.dropdown-item-icon.fas.fa-rocket.d-flex.justify-content-center.align-items-center
            span.dropdown-item-text = t('human_languages.racket')
          .dropdown-divider
          = link_to t('human_languages.ruby'), language_path('ruby'), class: 'dropdown-item'
          = link_to t('human_languages.elixir'), language_path('elixir'), class: 'dropdown-item'
          = link_to t('human_languages.go'), language_path('go'), class: 'dropdown-item'
      = nav_menu_item t('.about'), page_path(:about)
      = nav_menu_item t('.community'), ExternalLinks.hexlet_slack, target: '_blank'
      li.mr-md-auto
      li.nav-item.d-flex.align-items-center.order-last.order-md-0.mr-md-2
        = render 'layouts/shared/language_switcher'
      - if current_user.guest?
        = nav_menu_item t('.sign_in'), new_session_path
        = nav_menu_item t('.registration'), new_user_path
      - else
        li.nav-item.dropdown
          button.btn.nav-link.dropdown-toggle data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
            span.far.fa-user aria-hidden='true'
          span.sr-only
            = t('.toggle_user_info')
          .dropdown-menu.dropdown-menu-right
            .dropdown-item
              = current_user.email
            .dropdown-divider
            = link_to t('.profile'), edit_account_profile_path, class: 'dropdown-item'
            .dropdown-divider
            = link_to t('.sign_out'), session_path, method: :delete, class: 'dropdown-item'