services/app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  namespace :api do
    resources :lessons, only: [] do
      member do
        post :check
      end
    end
  end

  scope module: :web do
    root 'home#index'
    get 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    get '/403', to: 'errors#forbidden', as: :not_forbidden_errors
    get '/404', to: 'errors#not_found', as: :not_found_errors
    match '/500', to: 'errors#server_error', via: :all

    resources :pages, only: [:show]
    resource :session, only: %i[new create destroy]
    resource :locale, only: [] do
      member do
        get :switch
      end
    end
    resources :users, only: %i[new create]
    resource :remind_password, only: %i[new create]
    resource :password, only: %i[edit update]

    resources :languages, only: [:show] do
      scope module: :languages do
        resources :lessons, only: [:show] do
          get :next_lesson, on: :member
          get :prev_lesson, on: :member
        end
      end
    end

    namespace :admin do
      root 'home#index'

      resources :languages, only: %i[index new edit update create] do
        scope module: :languages do
          resources :versions, only: %i[index create]
        end
      end
    end

    namespace :account do
      resource :profile, only: %i[edit update destroy]
    end
  end
end

services/app/app/models/user/account.rb
# frozen_string_literal: true

class User::Account < ApplicationRecord
  belongs_to :user
end

services/app/app/controllers/web/account/application_controller.rb
# frozen_string_literal: true

class Web::Account::ApplicationController < Web::ApplicationController
end

services/app/app/controllers/web/account/profiles_controller.rb
# frozen_string_literal: true

class Web::Account::ProfilesController < Web::Account::ApplicationController
  before_action :authenticate_user!

  before_action do
    title :base
  end

  def edit
    @form = current_user.becomes(User::ProfileForm)
  end

  def update
    @form = current_user.becomes(User::ProfileForm)

    if @form.update(params[:user_profile_form])
      f(:success)

      redirect_to edit_account_profile_path
    else
      f(:error)

      render 'edit'
    end
  end

  def destroy
    current_user.mark_as_removed!
    sign_out

    f(:success)

    redirect_to root_path
  end
end

services/app/app/views/web/account/profiles/edit.html.slim
= content_for :meta do
  meta content='article' property='og:type'
  meta content=title property='og:title'
  meta content=edit_account_profile_url property='og:url'
  meta content=image_url('logo.png') property='og:image'
  link rel='canonical' href=edit_account_profile_url
  meta content=t('.meta_description') property='og:description'
  meta content=t('.meta_description') name='description'
  meta content="#{I18n.locale}" property='og:locale'

.row
  .col-sm-8.col-md-7.col-lg-6.mt-3.mb-5
    h1.mb-4.mb-lg-5 = t('.title', email: @form.email)
    = simple_form_for @form, url: account_profile_path do |f|
      = f.input :first_name, input_html: { 'data-testid' => 'first_name' }
      = f.input :last_name, input_html: { 'data-testid' => 'last_name' }
      = f.input :nickname, input_html: { 'data-testid' => 'nickname' }

      = f.submit class: 'btn btn-primary mt-4 btn-block', 'data-testid' => 'submit'

.row
  .col-sm-8.col-md-7.col-lg-6.mt-5
    = button_to t('.delete'), account_profile_path, class: 'btn btn-danger', method: :delete, data: { confirm: t('.confirm_delete') }