services/app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  namespace :api do
    resources :lessons, only: [] do
      member do
        post :check
      end
    end
  end

  scope module: :web do
    root 'home#index'
    get 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    get '/403', to: 'errors#forbidden', as: :not_forbidden_errors
    get '/404', to: 'errors#not_found', as: :not_found_errors
    match '/500', to: 'errors#server_error', via: :all

    resources :pages, only: [:show]
    resource :session, only: %i[new create destroy]
    resource :locale, only: [] do
      member do
        get :switch
      end
    end
    resources :users, only: %i[new create]
    resource :remind_password, only: %i[new create]
    resource :password, only: %i[edit update]

    resources :languages, only: [:show] do
      scope module: :languages do
        resources :lessons, only: [:show] do
          get :next_lesson, on: :member
          get :prev_lesson, on: :member
        end
      end
    end

    namespace :admin do
      root 'home#index'

      resources :languages, only: %i[index new edit update create] do
        scope module: :languages do
          resources :versions, only: %i[index create]
        end
      end
    end

    namespace :account do
      resource :profile, only: %i[edit update destroy]
    end
  end
end

services/app/app/controllers/web/remind_passwords_controller.rb
# frozen_string_literal: true

class Web::RemindPasswordsController < Web::ApplicationController
  before_action do
    title :base
  end

  def new
    @remind_password_form = RemindPasswordForm.new(User.new)
  end

  def create
    @remind_password_form = RemindPasswordForm.new(User.new)

    if @remind_password_form.validate(remind_password_params)
      user = @remind_password_form.user
      UserService.reset_password!(user)

      f(:success)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def remind_password_params
    params.require(:remind_password).permit(:email)
  end
end

services/app/app/views/web/remind_passwords/new.html.slim
= content_for :meta do
  meta content='webiste' property='og:type'
  meta content=title property='og:title'
  meta content=new_remind_password_url property='og:url'
  meta content=image_url('logo.png') property='og:image'
  link rel='canonical' href=new_remind_password_url
  meta content=t('.meta_description') property='og:description'
  meta content=t('.meta_description') name='description'
  meta content="#{I18n.locale}" property='og:locale'

.row.justify-content-center
  .col-sm-8.col-md-7.col-lg-6
    .card
      .card-body.p-4.p-lg-5
        h1.h3.mb-4.text-center = t('.forgot_password')
        = simple_form_for @remind_password_form, url: remind_password_path, wrapper: :no_labels_form do |f|
          = f.input :email
          = f.submit class: 'btn btn-primary btn-block'
        .text-center.mt-3
          = t('.trying_to_login')
          = link_to t('.login'), new_session_path, class: 'ml-1'
      .card-footer.text-center.p-3.p-md-4
          = t('.dont_have_account')
          = link_to t('.register'), new_user_path, class: 'ml-1'