services/app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  namespace :api do
    resources :lessons, only: [] do
      member do
        post :check
      end
    end
  end

  scope module: :web do
    root 'home#index'
    get 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    get '/403', to: 'errors#forbidden', as: :not_forbidden_errors
    get '/404', to: 'errors#not_found', as: :not_found_errors
    match '/500', to: 'errors#server_error', via: :all

    resources :pages, only: [:show]
    resource :session, only: %i[new create destroy]
    resource :locale, only: [] do
      member do
        get :switch
      end
    end
    resources :users, only: %i[new create]
    resource :remind_password, only: %i[new create]
    resource :password, only: %i[edit update]

    resources :languages, only: [:show] do
      scope module: :languages do
        resources :lessons, only: [:show] do
          get :next_lesson, on: :member
          get :prev_lesson, on: :member
        end
      end
    end

    namespace :admin do
      root 'home#index'

      resources :languages, only: %i[index new edit update create] do
        scope module: :languages do
          resources :versions, only: %i[index create]
        end
      end
    end

    namespace :account do
      resource :profile, only: %i[edit update destroy]
    end
  end
end

services/app/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include UserRepository
  include AASM

  has_secure_password validations: false

  # FIXME AASM has not without_state method. We have to change string comparsion to method that will check state
  validates :email, presence: true, uniqueness: { case_sensitive: false, conditions: -> { where.not(state: :removed) } }, 'valid_email_2/email': true

  has_many :lesson_members, class_name: 'Language::Lesson::Member', dependent: :destroy
  has_many :lessons, through: :lesson_members, class_name: 'Language::Lesson'
  has_many :language_members, class_name: 'Language::Member', dependent: :destroy
  has_many :accounts, dependent: :destroy

  aasm :state do
    state :active, initial: true
    state :initail
    state :waiting_confirmation
    state :removed

    event :activate do
      transitions to: :active
    end

    event :mark_as_removed do
      transitions to: :removed

      after do
        clean_fields
        remove_accounts
      end
    end
  end

  def initialize(attrs = nil)
    defaults = {
      locale: I18n.locale
    }
    attrs_with_defaults = attrs ? defaults.merge(attrs) : defaults
    super(attrs_with_defaults)
  end

  def guest?
    false
  end

  def valid_password?(password)
    return false if password_digest.nil?

    authenticate(password)
  end

  private

  def clean_fields
    fields = %w[
      first_name
      last_name
      nickname
      password_digest
      reset_password_token
      confirmation_token
      email
    ]

    fields.each do |field|
      send :"#{field}=", nil
    end
  end

  def remove_accounts
    accounts.clear
  end
end

services/app/app/models/user/account.rb
# frozen_string_literal: true

class User::Account < ApplicationRecord
  belongs_to :user
end

services/app/app/controllers/web/users_controller.rb
# frozen_string_literal: true

class Web::UsersController < Web::ApplicationController
  before_action do
    title :base
  end

  def new
    @user = User::SignUpForm.new
  end

  def create
    @user = User::SignUpForm.new(params[:user_sign_up_form])

    if @user.save
      sign_in @user

      f(:success)
      redirect_to root_path
    else
      render :new
    end
  end
end

services/app/app/views/web/users/new.html.slim
= content_for :meta do
  meta content='webiste' property='og:type'
  meta content=title property='og:title'
  meta content=new_user_url property='og:url'
  meta content=image_url('logo.png') property='og:image'
  link rel='canonical' href=new_user_url
  meta content=t('.meta_description') property='og:description'
  meta content=t('.meta_description') name='description'
  meta content="#{I18n.locale}" property='og:locale'

.row.justify-content-center
  .col-sm-8.col-md-7.col-lg-6
    .card
      .card-body.p-4.p-lg-5
        h1.mb-4.mb-lg-5.text-center = t('.sign_up')
        = simple_form_for @user, url: users_path, wrapper: :no_labels_form do |f|
          = f.input :email
          = f.input :password
          .form-group.mt-5
            = f.submit class: 'btn btn-primary mb-2 btn-block'
            = link_to auth_request_path('github'), class: 'btn btn-secondary btn-block' do
              span.fab.mr-2.fa-github
              = t('.sign_up_with_github')

      .card-footer.text-center.p-3.p-md-4
        span.mr-1 = t('.have_account')
        = link_to t('.sign_in'), new_session_path